name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: make main
      run: g++ src/Test.cpp src/Argument.cpp -o main 
      run: g++ main.cpp -o main
    - name: run
      run: ./main
    