name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    runs: 
      using: 'docker'
      image: 'gcc'

    steps:
    - uses: actions/checkout@v3
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: configure
      run: ./cofigure
    - name: make main
      run: make main
    - name: run
      run: ./main
    